#!/bin/bash

# Script to manage Drupal branch environments
# Usage: ./scripts/manage-branch.sh [create|destroy|list|status] [branch-name]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Helper functions
error() {
    echo -e "${RED}Error: $1${NC}" >&2
    exit 1
}

success() {
    echo -e "${GREEN}$1${NC}"
}

info() {
    echo -e "${YELLOW}$1${NC}"
}

# Sanitize branch name (same logic as buildspec)
sanitize_branch() {
    echo "$1" | tr '[:upper:]' '[:lower:]' | tr '_' '-' | sed 's/[^a-z0-9-]//g'
}

# Generate priority from branch name
generate_priority() {
    local branch=$1
    local hash=$(echo -n "$branch" | md5sum | tr -d 'a-z ' | cut -c 1-3)
    echo $((hash % 900 + 100))
}

# Create branch environment
create_branch() {
    local branch_name=$1
    local sanitized=$(sanitize_branch "$branch_name")
    local priority=$(generate_priority "$sanitized")
    local module_name="branch_${sanitized//-/_}"
    local tf_file="${PROJECT_DIR}/branch-${sanitized}.tf"

    info "Creating environment for branch: $branch_name"
    info "Sanitized name: $sanitized"
    info "Module name: $module_name"
    info "Listener priority: $priority"

    # Check if already exists
    if [ -f "$tf_file" ]; then
        error "Branch environment already exists: $tf_file"
    fi

    # Generate Terraform configuration
    cat > "$tf_file" <<EOF
# Auto-generated by manage-branch.sh
# Branch: $branch_name
# Created: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

module "$module_name" {
  source = "./modules/branch-environment"

  branch_name                 = "$sanitized"
  project_name                = var.project_name
  ecs_cluster_id              = aws_ecs_cluster.main.id
  ecs_cluster_name            = aws_ecs_cluster.main.name
  vpc_id                      = data.aws_vpc.existing.id
  private_subnet_ids          = local.subnet_ids
  ecs_hosts_security_group_id = aws_security_group.ecs_hosts.id
  alb_arn                     = aws_lb.main.arn
  alb_listener_arn            = var.certificate_arn != "" ? aws_lb_listener.https[0].arn : aws_lb_listener.http.arn
  alb_security_group_id       = aws_security_group.alb.id
  ecs_task_execution_role_arn = aws_iam_role.ecs_task_execution.arn
  ecs_task_role_arn           = aws_iam_role.ecs_task.arn
  aurora_endpoint             = aws_rds_cluster.aurora.endpoint
  aurora_database_name        = aws_rds_cluster.aurora.database_name
  aurora_secret_arn           = aws_secretsmanager_secret.aurora_master_password.arn
  s3_bucket_name              = aws_s3_bucket.drupal_files.id
  domain_suffix               = "review.example.gov"

  # Configuration
  drupal_image   = "drupal:10-apache"
  drupal_cpu     = 512
  drupal_memory  = 1024
  desired_count  = 1

  listener_rule_priority = $priority

  tags = merge(
    var.tags,
    {
      Branch    = "$branch_name"
      CreatedBy = "manage-branch.sh"
      CreatedAt = "$(date -u +"%Y-%m-%d")"
    }
  )
}

output "${module_name}_url" {
  description = "URL for $branch_name environment"
  value       = module.$module_name.url
}

output "${module_name}_service" {
  description = "ECS service name for $branch_name"
  value       = module.$module_name.service_name
}
EOF

    success "Generated Terraform configuration: $tf_file"

    # Apply
    cd "$PROJECT_DIR"
    info "Running terraform plan..."
    terraform plan -target="module.$module_name"

    read -p "Apply changes? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        terraform apply -auto-approve -target="module.$module_name"
        success "Branch environment created successfully!"

        # Get URL
        local url=$(terraform output -raw "${module_name}_url" 2>/dev/null || echo "")
        if [ -n "$url" ]; then
            success "Environment URL: $url"
        fi
    else
        info "Aborted. Configuration file created but not applied."
    fi
}

# Destroy branch environment
destroy_branch() {
    local branch_name=$1
    local sanitized=$(sanitize_branch "$branch_name")
    local module_name="branch_${sanitized//-/_}"
    local tf_file="${PROJECT_DIR}/branch-${sanitized}.tf"

    info "Destroying environment for branch: $branch_name"

    # Check if exists
    if [ ! -f "$tf_file" ]; then
        error "Branch environment does not exist: $tf_file"
    fi

    cd "$PROJECT_DIR"

    # Destroy
    info "Running terraform destroy..."
    terraform plan -destroy -target="module.$module_name"

    read -p "Destroy resources? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        terraform destroy -auto-approve -target="module.$module_name"
        rm "$tf_file"
        success "Branch environment destroyed successfully!"
    else
        info "Aborted."
    fi
}

# List all branch environments
list_branches() {
    info "Listing all branch environments..."
    cd "$PROJECT_DIR"

    local count=0
    for tf_file in branch-*.tf; do
        if [ -f "$tf_file" ]; then
            local branch=$(grep "# Branch:" "$tf_file" | awk '{print $3}')
            local created=$(grep "# Created:" "$tf_file" | cut -d':' -f2-)
            echo "  - $branch (created:$created)"
            count=$((count + 1))
        fi
    done

    if [ $count -eq 0 ]; then
        info "No branch environments found."
    else
        success "Total: $count branch environment(s)"
    fi
}

# Show status of a branch environment
status_branch() {
    local branch_name=$1
    local sanitized=$(sanitize_branch "$branch_name")
    local module_name="branch_${sanitized//-/_}"
    local tf_file="${PROJECT_DIR}/branch-${sanitized}.tf"

    if [ ! -f "$tf_file" ]; then
        error "Branch environment does not exist: $branch_name"
    fi

    info "Status for branch: $branch_name"
    cd "$PROJECT_DIR"

    # Get outputs
    local url=$(terraform output -raw "${module_name}_url" 2>/dev/null || echo "N/A")
    local service=$(terraform output -raw "${module_name}_service" 2>/dev/null || echo "N/A")

    echo "  URL:         $url"
    echo "  Service:     $service"
    echo "  Config File: $tf_file"

    # Check ECS service status if AWS CLI available
    if command -v aws &> /dev/null && [ "$service" != "N/A" ]; then
        local cluster=$(terraform output -raw ecs_cluster_name 2>/dev/null || echo "")
        if [ -n "$cluster" ]; then
            info "Fetching ECS service status..."
            aws ecs describe-services \
                --cluster "$cluster" \
                --services "$service" \
                --query 'services[0].[status,runningCount,desiredCount]' \
                --output text 2>/dev/null || echo "  Could not fetch service status"
        fi
    fi
}

# Main
main() {
    local command=$1
    local branch_name=$2

    case "$command" in
        create)
            if [ -z "$branch_name" ]; then
                error "Usage: $0 create <branch-name>"
            fi
            create_branch "$branch_name"
            ;;
        destroy)
            if [ -z "$branch_name" ]; then
                error "Usage: $0 destroy <branch-name>"
            fi
            destroy_branch "$branch_name"
            ;;
        list)
            list_branches
            ;;
        status)
            if [ -z "$branch_name" ]; then
                error "Usage: $0 status <branch-name>"
            fi
            status_branch "$branch_name"
            ;;
        *)
            echo "Drupal Branch Environment Manager"
            echo ""
            echo "Usage: $0 [command] [options]"
            echo ""
            echo "Commands:"
            echo "  create <branch-name>   Create a new branch environment"
            echo "  destroy <branch-name>  Destroy an existing branch environment"
            echo "  list                   List all branch environments"
            echo "  status <branch-name>   Show status of a branch environment"
            echo ""
            echo "Examples:"
            echo "  $0 create feature-auth"
            echo "  $0 list"
            echo "  $0 status feature-auth"
            echo "  $0 destroy feature-auth"
            exit 1
            ;;
    esac
}

main "$@"
